### ISSUE TITLE
selection of points/SNPs in the locuszoom plot

### ISSUE THREAD

**Issue by andreassteffen** [datavisyn/react-test#2]
sometimes selecting points (and turning them red) works, but sometimes i cannot select the point I want but another point or even multiple get selected (e.g. https://www.dropbox.com/s/euq9cspsjrhbptw/Screenshot%202016-12-06%2011.16.24.png?dl=0)

**Comment by sgratzl** [comment]
see also https://github.com/datavisyn/datavisyn-scatterplot/issues/3

**Comment by sgratzl** [comment]
moved to
